### PR TITLE
Pls add da block I made pls pls 

### PR DESCRIPTION
**Pull request by ItsLimeNade**
pls pls pls pls pls pls pls I am socially awkward pls pls pls pls pls pls plspls

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
ill accept this but in the future, change any required variable name you add to be something that isnt a common word for variables (basically just rename the perms variable you added to be something else so that people dont get errors)

**Comment by mrredo** [comment]
frick you jeremy

**Comment by mrredo** [comment]
> ill accept this but in the future, change any required variable name you add to be something that isnt a common word for variables (basically just rename the perms variable you added to be something else so that people dont get errors)

L

**Comment by JeremyGamer13** [comment]
oh god i have lost track of what menu i am in

**Comment by mrredo** [comment]
> oh god i have lost track of what menu i am in

bozo

**Pull request merged**
