### PR TITLE
New Blocks

### PR DESCRIPTION
**Pull request by Parham125**
My New Blocks

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
please explain what your blocks are supposed to do in their tooltips, and for blocks in the Other category, use this color: #D14081

**Comment by Parham125** [comment]
No Code block (you know what it was (it was on s4d py))

**Comment by JeremyGamer13** [comment]
> No Code block (you know what it was (it was on s4d py))

ye obviously i know but others might not since they probably havent realized s4d py exists yet

**Comment by Parham125** [comment]
The Blocks you put on them will not exported in js code

**Comment by JeremyGamer13** [comment]
ill merge it but ill change the tooltips

**Comment by JeremyGamer13** [comment]
actually nvm if your gonna do that then i can wait for you to update

**Comment by Parham125** [comment]
Done! @JeremyGamer13

**Pull request merged**
