### PR TITLE
test embed do not merge yet

### PR DESCRIPTION
**Pull request by EruptionGuy**

### CODE REVIEW

**Comment by frostzzone** [comment]
@EruptionGuy 
image

**Comment by frostzzone** [comment]
image

**Comment by EruptionGuy** [comment]
@frostzzone 
AAAA THAT WAS THE ERROR.

**Comment by EruptionGuy** [comment]
@frostzzone 
AAAA THAT WAS THE ERROR.

**Comment by EruptionGuy** [comment]
I'll close this for now

**Pull request closed without merging**
