### PR TITLE
EMBED hopefully it's gonna work this time

### PR DESCRIPTION
**Pull request by EruptionGuy**

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
i see you added another embed, if it works should i merge it instantly or do you still need to do stuff

**Comment by JeremyGamer13** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'Math')

**Comment by EruptionGuy** [comment]
wait what

**Review by JeremyGamer13 — DISMISSED** [review]
Uncaught TypeError: Cannot read properties of undefined (reading 'Math')
    at 56d7 (main.js:33:19)
    at l (bootstrap:79:22)
    at 0 (app.eac36f90.js:1:1562)
    at l (bootstrap:79:22)
    at n (bootstrap:45:15)
    at bootstrap:152:10
    at app.eac36f90.js:1:1532
56d7 @ main.js:33
l @ bootstrap:79
0 @ app.eac36f90.js:1
l @ bootstrap:79
n @ bootstrap:45
(anonymous) @ bootstrap:152
(anonymous) @ app.eac36f90.js:1

**Comment by JeremyGamer13** [comment]
i got that on the preview, the page is entirely black

**Comment by EruptionGuy** [comment]
hmm that's not my issue though

**Comment by EruptionGuy** [comment]
it's probably a bootstrap issue

**Comment by JeremyGamer13** [comment]
oh wait it looks like its a problem with the mutator, i just checked

**Comment by EruptionGuy** [comment]
wait a minute, I didn't change main.js at all
image

**Comment by JeremyGamer13** [comment]
yeah main.js isnt the problem

**Comment by EruptionGuy** [comment]
You know what? I'm just gonna merge. If it doesn't work then I'll revert

**Pull request merged**
