### PR TITLE
A block that Jeremy forgot to add from 470

### PR DESCRIPTION
**Pull request by EruptionGuy**

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
missing some language file stuff still

**Comment by EruptionGuy** [comment]
@JeremyGamer13

`"message0": "start thread on message %7 with name%1 auto archive after%2%4then%6%3if not enough server boost level%8%5",`

**Comment by JeremyGamer13** [comment]
nvm if rogr

**Comment by JeremyGamer13** [comment]
> @JeremyGamer13
> 
> `"message0": "start thread on message %7 with name%1 auto archive after%2%4then%6%3if not enough server boost level%8%5",`

i meant the drop down options but those already are defined and i didnt remember that

**Pull request merged**
